### PR TITLE
fix: enhance auth type

### LINKED ISSUE #422: Setting the auth doesn't include relations
Given this schema:

```ts
model Session {
    id                   String   @id
    expiresAt            DateTime
    token                String
    createdAt            DateTime
    updatedAt            DateTime
    ipAddress            String?
    userAgent            String?
    userId               String
    user                 User     @relation(fields: [userId], references: [id], onDelete: Cascade)
    activeOrganizationId String?

    @@schema('auth')
    @@unique([token])
    @@auth
}
```

I would like to be able to set the user of the `@@auth` model as such:

```ts
   const client = zenstackClientWithPolicies.$setAuth({
      ...session,
      user: { ... },  // <--- Type Error: user property doesn't not exist
    })
```

If I recall, this was possible in `V2`:

```ts
enhance(prisma, {
  user: {
    ...session,
    user,
  },
}),
```

Relevant discord discussion: https://discord.com/channels/1035538056146595961/1440320890142326926

### PR DESCRIPTION
**Pull request by genu**
Fixes #422 

## Summary by CodeRabbit

* **Refactor**
  * Improved auth type handling to correctly support nested relations and array relation shapes.

* **API Changes**
  * Made a core model result type publicly available for more consistent ORM typings.

* **New Features**
  * Added generated schema and model type aliases to simplify strongly-typed ORM usage.

* **Tests**
  * Added a regression test verifying auth inference with nested related objects.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: packages/orm/src/client/contract.ts [hunk 1]
```diff
@@ -810,11 +820,23 @@ export type ModelOperations<Schema extends SchemaDef, Model extends GetModels<Sc
 
 //#region Supporting types
 
+/**
+ * Type for auth context that includes both scalar and relation fields.
+ * Relations are recursively included to allow nested auth data like { user: { profile: { ... } } }
+ */
+type AuthModelType<Schema extends SchemaDef, Model extends GetModels<Schema>> = {
+    [Key in NonRelationFields<Schema, Model>]?: MapModelFieldType<Schema, Model, Key>;
```
Comment (ymc9) [inline packages/orm/src/client/contract.ts]: There's a `DefaultModelResult` type in crud-types.ts. I think we can export it and use here. It'll provide all scalar fields (we need to wrap it with Partial though). We can use it to recurse into relation fields too.

**Review by ymc9 — APPROVED** [review]
LGTM! Thank you!
